spring:
  profiles:
    active: dev

---

server:
  port: 8001
spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql:///cloudDB01
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.athena.springcloud.entities
  mapper-locations: 
  - classpath: mybatis/mapper/**/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true

---

server:
  8   port: 8001
  9 spring:
 10   profiles: test
 11   application:
 12     name: microservicecloud-config-dept-client
 13   datasource:
 14     type: com.alibaba.druid.pool.DruidDataSource
 15     driver-class-name: org.gjt.mm.mysql.Driver
 16     url: jdbc:mysql:///cloudDB02
 17     username: root
 18     password: 123456
 19     dbcp2:
 20       min-idle: 5
 21       initial-size: 5
 22       max-total: 5
 23       max-wait-millis: 200
 24 mybatis:
 25   config-location: classpath:mybatis/mybatis.cfg.xml
 26   type-aliases-package: com.athena.springcloud.entities
 27   mapper-locations: 
 28   - classpath: mybatis/mapper/**/*.xml
 29 
 30 eureka:
 31   client:
 32     service-url:
 33       defaultZone: http://eureka7001.com:7001/eureka
 34   instance:
 35     instance-id: dept-8001.com
 36     prefer-ip-address: true
