eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-8761:8761/eureka,http://eureka-8762:8762/eureka
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:myslq://localhost:3306/springCloud
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
